Replace --no-create with --no-config
powder no longer use the --no-create option

```shell
ERROR: "powder link" was called with arguments ["lapi", "--no-create"]
Usage: "powder link"
```